api7/lua-resty-radixtree

- lib/resty/radixtree.lua
- t/vars.t
> feature: support more operators when compare vars.

- lib/resty/radixtree.lua
- src/easy_rax.c
- src/easy_rax.h
fix: https://github.com/iresty/apisix/issues/590
> bugfix: reused the iterator object.

- README.md
- lib/resty/radixtree.lua
- t/filter-fun.t
- t/handler.t
- t/host.t
- t/multiple.t
- t/path.t
- t/remote.t
- t/sanity.t
- t/vars.t
> change: used `paths`, `hosts`, `remote_addrs`, `methods` and `vars` to

- Makefile
- README.md
- lib/resty/radixtree.lua
- src/easy_rax.c
- src/easy_rax.h
Performance is about 20+% improvement
> optimize: only supported to store integer index.

- lib/resty/radixtree.lua
- t/parameter.t
record host, uri, method which matches the current request.
> feature: record which matches the current request.

- lib/resty/radixtree.lua
- t/parameter.t
related issue: https://github.com/apache/apisix/issues/2008
> bugfix: failed to match route when no `matched` in opts.

- lib/resty/radixtree.lua
- t/parameter.t
fix https://github.com/apache/apisix/issues/2058
> bugfix: return false if not matched the fully request URI.

- benchmark/match-hosts.lua
- lib/resty/radixtree.lua
- t/filter-fun.t
1. avoid varg to make host match JIT compiled
2. avoid calling lj_tab_len too many times
> optimize: make host match 20x faster

- lib/resty/radixtree.lua
- t/matched.t
> fix: record which matches the current request error. 

- lib/resty/radixtree.lua
- t/lib/ljson.lua
- t/parameter.t
> test: use `ljson` to encode lua table, we can got same encode result.

- README.md
fix the description of dependence
> doc: fix the description of dependence

- lib/resty/radixtree.lua
- src/easy_rax.c
- src/easy_rax.h
- t/rax.t
radix_tree_find return raxNotFound
> fix: handle raxNotFound

- README.md
go the result from Macbook 2019 16inch
> doc: udpate the benchmark result

- .github/workflows/release.yml
- .github/workflows/test.yml
update luarocks to 3.8.0
fix  https://github.com/api7/lua-resty-radixtree/issues/109
> chore: update luarocks version to 3.8.0

- lib/resty/radixtree.lua
- t/parameter.t
Closes #108
Fix the behaviour of this PR: #58
> fix: no opts option should work fine

- lib/resty/radixtree.lua
- t/sanity.t
fix: https://github.com/apache/apisix/issues/6766
> feat: add PURGE method

- .github/workflows/release.yml
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> feat: release v2.8.2

- README.md
This PR mainly changes company information.
> docs: update company information

- README.md
Improves the documentation of the library to be clearer for users.
Please view the preview here: https://github.com/api7/lua-resty-radixtree/tree/docs/improve-docs/1#readme
> docs: improve library documentation

- rockspec/lua-resty-radixtree-2.8.3-0.rockspec
Add incremental radixtree update API
> feat: release v2.8.3

- rockspec/lua-resty-radixtree-2.9.2-0.rockspec
release a new version with a fix: #150
> chore: release v2.9.2
